# Generated by Django 3.2.7 on 2021-12-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itforce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='valie',
        ),
    ]
