# Generated by Django 3.2.7 on 2021-12-03 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itforce', '0002_remove_orderstatus_valie'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
